---
- name: Create Organization
  hosts: localhost

  tasks:

    - name: Create Organization
      ansible.controller.organization:
        name: "DO374_Demo"
        description: "DO374 Demo Organization"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
