---
- name: Demo to Fetch Files from Remote System
  hosts: servera
  tasks:
    - name: Fetch file from system
      fetch:
        src: /etc/hostname
        dest: ./{{ inventory_hostname }}_etc_hostname
        flat: yes
