---
- name: First task
  hosts: servera.lab.example.com
  gather_facts: false
  become: true

  tasks:
    - name: Add groups
      ansible.builtin.group:
        name: "{{ item['key'] }}"
        gid: "{{ item['value']['gid'] }}"
        state: present
      loop: "{{ rgroups | dict2items }}"
